version: "3.9"

services:
  load_balancer:
    build: ./load_balancer
    ports:
      - "9999:9999"
    depends_on:
      - backend1
      - backend2
    networks:
      - backend
      - payment-processor

  backend1:
    build: ./backend
    environment:
      - BACKEND_PORT=8021
    command: ["/main"]
    expose:
      - "8021"
    networks:
      - backend
      - payment-processor
    depends_on:
      - mysql_db
  backend2:
    build: ./backend
    environment:
      - BACKEND_PORT=8022
    command: ["/main"]
    expose:
      - "8022"
    networks:
      - backend
      - payment-processor
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3308:3306"
    networks:
      - backend
      - payment-processor
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=example_db
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
      - payment-processor
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
